# Generated by Django 4.2.4 on 2024-09-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
