# Generated by Django 4.2.4 on 2024-09-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
