# Generated by Django 4.2.4 on 2024-09-26 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0006_remove_course_instructor_remove_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('previous', 'Previous'), ('latest', 'Latest'), ('upcoming', 'Upcoming')], default='latest', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('VSO', 'VSO'), ('Trainer', 'Trainer'), ('Admin', 'Admin')], default='VSO', max_length=10)),
                ('status', models.CharField(choices=[('speed_signoff', 'Speed Sign-Off'), ('double_cab', 'Double Cab')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
