# Generated by Django 4.2.4 on 2024-09-26 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0008_course_remove_userprofile_user_delete_qareport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('report_reference', models.CharField(max_length=100, unique=True)),
                ('result', models.CharField(choices=[('Red', 'Red'), ('Amber', 'Amber'), ('Green', 'Green')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
