# Generated by Django 4.2.4 on 2024-09-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_qareport'),
    ]

    operations = [
        migrations.AddField(
            model_name='qareport',
            name='reference_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
