# Generated by Django 4.2.4 on 2024-09-27 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0010_qareport_reference_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('VSO', 'VSO'), ('Trainer', 'Trainer'), ('Admin', 'Admin')], max_length=20)),
                ('status', models.CharField(choices=[('Speed Sign-off', 'Speed Sign-off'), ('Double Cab', 'Double Cab')], max_length=20)),
                ('initial_training_records', models.TextField(blank=True)),
                ('investigations', models.TextField(blank=True)),
                ('pcn_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='certificates',
            field=models.ManyToManyField(blank=True, related_name='certificates', through='lms.Certificate', to=settings.AUTH_USER_MODEL),
        ),
    ]
