# Generated by Django 4.2.4 on 2024-09-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_trainingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='supporting_document',
            field=models.URLField(blank=True, null=True),
        ),
    ]
