# Generated by Django 4.2.4 on 2024-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_alter_trainingrecord_supporting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='supporting_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='training_documents/'),
        ),
    ]
