# Generated by Django 4.2.4 on 2024-09-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_trainingrecord_supporting_document_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrecord',
            name='supporting_document',
        ),
    ]
