# Generated by Django 4.2.4 on 2024-09-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_remove_trainingrecord_supporting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='training_documents/'),
        ),
    ]
