# Generated by Django 4.2.4 on 2024-09-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_trainingrecord_supporting_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrecord',
            name='supporting_document',
        ),
    ]
