# Generated by Django 4.2.16 on 2024-10-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_remove_trainingrecord_supporting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='qa_team', to='lms.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('VSO', 'VSO'), ('Trainer', 'Trainer'), ('QA', 'QA'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
