# Generated by Django 4.2.16 on 2024-10-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_profile_team_members_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team_members',
        ),
        migrations.AddField(
            model_name='profile',
            name='assigned_qa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsos', to='lms.profile'),
        ),
    ]
