# Generated by Django 4.2.16 on 2024-10-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_remove_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('VSO', 'VSO'), ('Trainer', 'Trainer'), ('QA', 'QA')], max_length=20),
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_title', models.CharField(max_length=200)),
                ('date_opened', models.DateField(auto_now_add=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('report', models.TextField(blank=True)),
                ('vso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_reports', to='lms.profile')),
            ],
        ),
    ]
