# Generated by Django 4.2.16 on 2024-10-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_remove_profile_assigned_qa_profile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('On-road Testing', 'On-road Testing'), ('Refresher required', 'Refresher required'), ('Off road', 'Off road')], default='On-road Testing', max_length=20),
        ),
    ]
